### ISSUE TITLE
Math formulas in LaTeX

### ISSUE THREAD

**Issue by platinumthinker** [Xeway/big-math#1]
Y can use LaTeX instead images inside repo, like this 
https://github.blog/2022-05-19-math-support-in-markdown/

**Comment by Xeway** [comment]
@platinumthinker just finished the change from images to LaTex.
Thanks so much for your advice! The README is way simpler now!

**Comment by Xeway** [comment]
@platinumthinker it's updated on https://pkg.go.dev/github.com/Xeway/big-math
And as you see pkg.go.dev doesn't support LaTex...
Any thoughts ?

**Comment by platinumthinker** [comment]
Hi! Sorry for the delay.

About problem: i haven't experience with published golang packages on pkg.go.dev and look around:
(https://pkg.go.dev/github.com/charmbracelet/gum, https://github.com/charmbracelet/gum)
(https://pkg.go.dev/github.com/urfave/cli/v2, https://github.com/urfave/cli) 
Some popular packages have different readme on github and pkg.go.dev and haven't idea how it happens.
But general idea: some packages have full readme on github and short docs on pkg.go.dev (general purposes, api)

**Comment by Xeway** [comment]
Hey, thanks for your answer.

So I followed your advice and moved the explaination with LaTex formulas into another .md file.
